name: Build and Deploy
description: 'Build your React App on every push to your main branch and publish it to a branch'
branding:
  icon: 'https://img.icons8.com/?size=100&id=Vra58PN2KmI5&format=png&color=000000'
  color: 'gray-dark'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build and Deploy
      uses: mmedoo/react-on-pages
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
