name: Build React on Push
description: 'Build your React App on every push to your main branch and publish it to a branch'
branding:
  icon: 'anchor'
  color: 'gray-dark'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build and Deploy
      uses: mmedoo/react-on-pages
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
