name: 'Build and Publish React'

branding:
  color: 'gray-dark'
  icon: 'anchor'
  
description: 'A GitHub Action to build and publish your React App'

inputs:

  GITHUB_TOKEN:
    description: 'GitHub token for authentication'
    required: true
    
  TARGET_DIRECTORY:
    description: 'Directory in which the files shall be placed (default is root)'
    required: false
    default: '.'
    
  BRANCH_NAME:
    description: 'Branch name to which the build artifacts will be pushed (default is build)'
    required: false
    default: 'build'
    
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Cache npm dependencies
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      shell: bash
      run: npm ci
      
    - name: Build the app
      shell: bash
      run: |
        CI=false npm run build
        
    - name: Publish build artifacts
      shell: bash
      if: success()
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
          
      run: |
      
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git fetch origin
        
        BRANCH_NAME="${{ inputs.BRANCH_NAME }}"
        git switch $BRANCH_NAME || git switch --orphan $BRANCH_NAME

        
        for item in $(ls -A); do
          if [ "$item" != "build" ] && [ "$item" != ".git" ]; then
            echo "Removing $item"
            rm -rf "$item"
          fi
        done
        
        cp -r ./build/* "$TARGET_DIR" || cp -r ./build/* .
        rm -rf build

        ls -A
        
        git add .
        git commit -m 'Publish build artifacts'
        git push origin $BRANCH_NAME --force
